import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'

async function createAccount(page: Page) {
  const name = `test-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`
  await page.goto('/')
  await page.getByLabel('Test name', { exact: true }).fill(name)
  await page.getByLabel('Test password', { exact: true }).fill('local-test-only')
  await page.getByRole('button', { name: 'Create test account', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'My Study Check-In' })).toBeVisible()
  return name
}
async function checkIn(page: Page, choices: string[], nickname = 'Test Learner') {
  await page.getByLabel('My nickname').fill(nickname)
  await page.getByRole('button', { name: "Let's begin" }).click()
  for (const [index, choice] of choices.entries()) {
    await page.getByRole('radio', { name: choice, exact: true }).check()
    await page.getByRole('button', { name: index === 4 ? 'See my helpers' : 'Next', exact: true }).click()
  }
}
async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
}
test('check-in, steps, planning, completion, persistence, reflection, and account isolation', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  const name = await createAccount(page)
  await checkIn(page, ['Not often', 'Often', 'Not often', 'Not often', 'Sometimes'])
  await expect(page.getByRole('checkbox', { name: /Small steps/ })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: /Plan ahead/ })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: /Focus timer/ })).not.toBeChecked()
  await page.getByRole('button', { name: 'Save my helpers' }).click()
  await page.getByRole('button', { name: 'Add homework', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('What is the homework?').fill('Book report')
  await dialog.getByRole('combobox', { name: 'Subject', exact: true }).selectOption('Reading')
  await dialog.getByLabel('Due date').fill('2026-12-20')
  await dialog.getByLabel('Step template').selectOption('Book report')
  await expect(dialog.getByLabel('Step 1', { exact: true })).toHaveValue('Choose my book')
  const today = await page.evaluate(() => { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}` })
  await dialog.getByLabel('Day', { exact: true }).first().fill(today)
  await dialog.getByRole('button', { name: 'Save homework' }).click()
  await expect(dialog).not.toBeVisible()
  const task = page.locator('article.task').filter({ has: page.getByRole('heading', { name: 'Book report', exact: true }) })
  await task.getByRole('checkbox', { name: /Choose my book/ }).check()
  await expect(task.getByText('1 of 4 steps done')).toBeVisible()
  await page.reload()
  await expect(task.getByRole('checkbox', { name: /Choose my book/ })).toBeChecked()
  await page.getByRole('button', { name: 'My plan', exact: true }).click()
  await page.getByRole('button', { name: 'Add to day' }).click()
  await expect(page.getByRole('button', { name: 'Remove from day' })).toBeVisible()
  if (testInfo.project.name === 'desktop') await page.screenshot({ path: 'public/docs/screenshots/plan.png', fullPage: true })
  await page.getByRole('button', { name: 'My homework', exact: true }).click()
  await expect(task.getByText(/Planned Today/)).toBeVisible()
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('homework.png'), fullPage: true })
  if (testInfo.project.name === 'desktop') await page.screenshot({ path: 'public/docs/screenshots/homework.png', fullPage: true })
  await task.getByRole('button', { name: 'Complete Book report', exact: true }).click()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(task.getByText('4 of 4 steps done')).toBeVisible()
  await task.getByRole('checkbox', { name: /Choose my book/ }).click()
  await page.getByRole('button', { name: 'To do', exact: true }).click()
  await expect(task.getByText('3 of 4 steps done')).toBeVisible()
  await task.getByRole('button', { name: 'Edit Book report' }).click()
  await dialog.getByLabel('What is the homework?').fill('My book report')
  await dialog.getByRole('button', { name: 'Save homework' }).click()
  await expect(page.locator('article.task h3')).toHaveText('My book report')
  await page.getByRole('button', { name: 'My progress', exact: true }).click()
  await page.getByRole('radio', { name: 'Good', exact: true }).check()
  await page.getByLabel('What helped? What could you try next?').fill('Small steps helped me start.')
  await page.getByRole('button', { name: 'Save reflection' }).click()
  await expect(page.locator('.reflection-history')).toContainText('Small steps helped me start.')
  if (testInfo.project.name === 'desktop') await page.screenshot({ path: 'public/docs/screenshots/progress.png', fullPage: true })
  await page.reload()
  await page.getByRole('button', { name: 'My progress', exact: true }).click()
  await expect(page.locator('.reflection-history')).toContainText('Small steps helped me start.')
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await createAccount(page)
  await checkIn(page, ['Not often', 'Not often', 'Not often', 'Often', 'Not often'], 'Another Learner')
  await page.getByRole('button', { name: 'Save my helpers' }).click()
  await expect(page.locator('article.task')).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Focus timer' })).toBeVisible()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByRole('button', { name: 'Already have a test account? Sign in' }).click()
  await page.getByLabel('Test name', { exact: true }).fill(name)
  await page.getByLabel('Test password', { exact: true }).fill('local-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('article.task h3')).toHaveText('My book report')
  await page.getByRole('button', { name: 'Delete My book report', exact: true }).click()
  await page.getByRole('button', { name: 'Keep it', exact: true }).click()
  await expect(page.locator('article.task')).toHaveCount(1)
  await page.getByRole('button', { name: 'Delete My book report', exact: true }).click()
  await page.getByRole('button', { name: 'Delete homework', exact: true }).click()
  await expect(page.locator('article.task')).toHaveCount(0)
  expect(errors).toEqual([])
})
test('helper changes, retaking check-in, timer controls, and responsive screens', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.locator('.login-art img')).toBeVisible()
  expect(await page.locator('.login-art img').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true)
  await page.getByRole('link', { name: 'Full documentation' }).click()
  await expect(page).toHaveURL(/\/docs$/)
  await expect(page.getByRole('heading', { name: 'Documentation' })).toBeVisible()
  await expect(page.getByRole('treeitem')).toHaveCount(6)
  const guideImage = page.locator('.docs-screenshot img')
  await expect.poll(() => guideImage.evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true)
  await page.getByRole('treeitem', { name: /Build a plan for today/ }).click()
  await expect(page.getByRole('heading', { name: 'Build a plan for today' })).toBeVisible()
  await expect(guideImage).toHaveAttribute('src', '/docs/screenshots/plan.png')
  await noOverflow(page)
  await page.getByRole('link', { name: 'Back to LearnTrack' }).click()
  await expect(page.getByRole('heading', { name: 'How LearnTrack works' })).toBeVisible()
  await expect(page.locator('.guide-steps > li')).toHaveCount(4)
  await page.getByRole('link', { name: 'Read the user guide' }).click()
  await expect(page).toHaveURL(/\/docs$/)
  await page.getByRole('link', { name: 'Back to LearnTrack' }).click()
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('login.png'), fullPage: true })
  await createAccount(page)
  await page.getByLabel('My grade').selectOption('K-2')
  await checkIn(page, ['Not often', 'Not often', 'Not often', 'Often', 'Not often'])
  await page.screenshot({ path: testInfo.outputPath('check-in.png'), fullPage: true })
  if (testInfo.project.name === 'desktop') await page.screenshot({ path: 'public/docs/screenshots/check-in.png', fullPage: true })
  await page.getByRole('button', { name: 'Save my helpers' }).click()
  await expect(page.locator('.save-status')).toHaveText('Your helpers are saved.')
  const timer = page.getByRole('region', { name: 'Focus timer' })
  await expect(timer.getByRole('timer')).toHaveText('05:00')
  await page.clock.install()
  await timer.getByLabel('Timer minutes').selectOption('1')
  await timer.getByRole('button', { name: 'Start', exact: true }).click()
  await page.clock.fastForward(2000)
  await expect(timer.getByRole('timer')).toHaveText('00:58')
  await timer.getByRole('button', { name: 'Pause', exact: true }).click()
  await page.clock.fastForward(10000)
  await expect(timer.getByRole('timer')).toHaveText('00:58')
  await timer.getByRole('button', { name: 'Start', exact: true }).click()
  await page.clock.fastForward(60000)
  await expect(timer.getByRole('status')).toContainText('Session finished')
  await timer.getByRole('button', { name: 'Break', exact: true }).click()
  await expect(timer.getByRole('timer')).toHaveText('05:00')
  await timer.getByRole('button', { name: 'Reset timer' }).click()
  await page.getByRole('button', { name: 'My helpers', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Enable Small steps', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Enable Small steps', exact: true })).toBeChecked()
  await page.getByRole('checkbox', { name: 'Enable Focus timer', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Enable Focus timer', exact: true })).not.toBeChecked()
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('helpers.png'), fullPage: true })
  if (testInfo.project.name === 'desktop') await page.screenshot({ path: 'public/docs/screenshots/helpers.png', fullPage: true })
  await page.getByRole('button', { name: 'My homework', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Focus timer' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Add homework', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('checkbox', { name: 'Small steps' })).toBeChecked()
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('editor.png'), fullPage: true })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByRole('button', { name: 'My helpers', exact: true }).click()
  await page.getByRole('button', { name: 'Retake my check-in' }).click()
  await checkIn(page, ['Often', 'Not often', 'Not often', 'Not often', 'Not often'])
  await expect(page.getByRole('checkbox', { name: /Homework checklist/ })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: /Focus timer/ })).not.toBeChecked()
  await page.getByRole('button', { name: 'Save my helpers' }).click()
  await expect(page.locator('.helper-rail')).toContainText('Homework checklist')
})